### ISSUE TITLE
Add Theme Variants causes an error

### ISSUE THREAD

**Issue by eck4god** [SebastianDietrich/moneyfield#2]
When adding a theme variant to right align the values an error is thrown on line 542, java.lang.NoSuchMethodError.

**Comment by SebastianDietrich** [comment]
That is probably due to a version incompatibility. Should work with Vaadin 23.X and below.
Can you please confirm that you are on Vaadin 24.X?

**Comment by SebastianDietrich** [comment]
I've checked it with a project that uses Vaadin 24.X and got the same error.
--> deployed a new version (2.2.0) that fixes that issue.
